# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.0'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Pay-As-You-Go(46794ed6-e73a-465d-8d00-b943ffadfdf4)'
    backendAzureRmResourceGroupName: 'amdocs_tfstate'
    backendAzureRmStorageAccountName: 'amdocstfstate'
    backendAzureRmContainerName: 'amdocs'
    backendAzureRmKey: 'test.tfstate'